import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="grid grid-cols-10 h-screen">
  <div className="col-span-2  w-full">
    <Navbar />
  </div>
  <div className="col-span-8 flex flex-col p-5">
    <div className="bg-[#F9F9FC] flex-grow p-3 rounded-md overflow-auto">
      {children}
    </div>
  </div>
</main>

  );
}
